### ISSUE TITLE
Feature request: Disable individual goblins

### ISSUE THREAD

**Issue by greencopper** [FreeLikeGNU/mobs_goblins#5]
Hi

Really great mobs mod! Add lots of fun.

It would be really cool with an easy way to disable/enable which ever of the goblins one would like to use.

Kind regards.

**Comment by FreeLikeGNU** [comment]
in the goblins.lua, at the end you will see where goblins are spawned (one for each line).  You can comment them out with -- at the beginning of the line like this:

`-- mobs_goblins:spawn_specific("mobs_goblins:goblin_cobble", {"group:stone"}, "air", 0, 50, 1, 10, 3, -30000 , 0)`
