### ISSUE TITLE
[Patch] Undefined Global Variable 'singleplayer'

### ISSUE THREAD

**Issue by AntumDeluge** [FreeLikeGNU/mobs_goblins#7]
I wanted to suggest the following patch:

[mobs_goblins-goblin_traps.lua.diff.zip](https://github.com/FreeLikeGNU/mobs_goblins/files/416851/mobs_goblins-goblin_traps.lua.diff.zip)
- Creates local variable 'singleplayer' from 'minetest.is_singleplayer()'
  - Fixes warning about 'Undeclared global variable "singleplayer''

**Comment by FreeLikeGNU** [comment]
applied PR.  Thanks!
